# Generated by Django 4.2 on 2025-09-06 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('dataset_size', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Profile bio text')),
                ('friends_count', models.PositiveIntegerField(help_text='Number of friends/followers')),
                ('posts_per_week', models.PositiveIntegerField(help_text='Average posts per week')),
                ('account_age_days', models.PositiveIntegerField(default=0, help_text='Account age in days')),
                ('profile_picture', models.BooleanField(default=True, help_text='Has profile picture')),
                ('verified', models.BooleanField(default=False, help_text='Is verified account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for flagging')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Fake'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fake', models.BooleanField(help_text='ML prediction: True if fake, False if genuine')),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1)')),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('features_used', models.JSONField(default=dict, help_text='Features used for prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection_app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
