# Generated by Django 4.2 on 2025-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts_per_week',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.PositiveIntegerField(default=0, help_text='Total number of posts'),
        ),
    ]
